export const CHANGE_BUTTON_TEXT = 'CHANGE_BUTTON_TEXT';

export const CHANGE_TREE_CLASS = 'CHANGE_TREE_CLASS';

export const CHANGE_APPLE1_CLASS = 'CHANGE_APPLE1_CLASS';

export const CHANGE_APPLE2_CLASS = 'CHANGE_APPLE2_CLASS';

export const CHANGE_APPLE3_CLASS = 'CHANGE_APPLE3_CLASS';




